### PR TITLE
additional fixes/tweaks

### PR DESCRIPTION
**Pull request by ttilley**
This batch of changes is primarily sandbox related. I needed to do a fair bit of searching and debugging for this one... It doesn't help that the official documentation is incorrect. See the statement from an apple employee here (requires access to devforum): https://devforums.apple.com/message/587382#587382
- removed `LSRegisterURL`. In a dev forum discussion an apple employee admitted the documentation was incorrect and that `LSRegisterURL` should _never_ be called by a sandboxed application.
- replaced startAtLogin getter with one that's more sandbox friendly, if slightly slower and messier
- added semi-cached 'enabled' property that's more intuitive to track via KVO. `startAtLogin` and `setStartAtLogin:` save state to this property as it changes, allowing one to instead track `enabled` and avoid API calls altogether on read. writing to `enabled` simply calls `setStartAtLogin:`.
- inform KVO of the non-automatic behavior for properties 'startAtLogin' and 'enabled'
- remove potentially non-sandbox-safe `remove` method.
- re-indent everything like the whitespace nazi i am
- figured I might as well add my name to the copyright at this point

### CODE REVIEW

**Comment by alexzielenski** [comment]
I feel like a lot of your changes are extraneous and unnecessary:
1. LSRegisterURL can stay since even though it fails, it does not stop the register process. (Works for unsandboxed)
2. Yours is not more sandbox friendly. It consumes more ram, takes more time and is not needed. The old one worked finely in a sandboxed environment
3. Although this is useful, it adds complication to the code and isn't really needed seeing as the startAtLogin getter is probably not going to be called more than 3-4 times in one run of the app. (And since I'm sticking with my old startAtLogin, it doesn't make as much sense to use a cached bool)
4. Not seeing how it is not sandbox safe. It uses the ServiceManagement functions provided by Apple for this purpose.

**Comment by ttilley** [comment]
I have a menulet. A menu item had its 'value' bound to (effectively) AppDelegate.loginController.startAtLogin. Every time the menu is opened a method was called (debug NSLog statements were added to verify). That's more than 3-4 times in one run of an app.

Despite this, the initial state was always OFF. Click, set startAtLogin to YES via binding, see console messages verifying this is the case... awesome. Restart, open the menu again, and the menu item's state is back to OFF. I could log out and log back in, have the application launch, and still see that menu item OFF with no checkmark.

A little research and it seems that `SMJobCopyDictionary` doesn't always behave itself when sandboxed. Testing this myself, I have two lines of code:

``` objc
CFStringRef cfIdentifier = (CFStringRef)CFBridgingRetain(_identifier);
CFDictionaryRef cfDict = SMJobCopyDictionary(kSMDomainUserLaunchd, cfIdentifier);
```

Setting a breakpoint to observe line by line... cfDict is always set to NIL. It doesn't matter whether or not the app is configured to start at login, that dict is always NIL.

```
Printing description of cfDict:
Can't print the description of a NIL object.
```

Same run of the application, a few lines down, is the implementation you rejected:

``` objc
    // the easy and sane method (SMJobCopyDictionary) can pose problems when sandboxed. -_-
    CFArrayRef cfJobDicts = SMCopyAllJobDictionaries(kSMDomainUserLaunchd);
    NSArray* jobDicts = CFBridgingRelease(cfJobDicts);

    if (jobDicts && [jobDicts count] > 0) {
        for (NSDictionary* job in jobDicts) {
            if ([_identifier isEqualToString:[job objectForKey:@"Label"]]) {
                isEnabled = [[job objectForKey:@"OnDemand"] boolValue];
                break;
            }
        }
    }
```

My breakpoint is set on the line with `isEnabled =`. I go to inspect the job object and low and behold! My identifier, in a dictionary, alongside valid useful data. Printing this out in GDB:

```
(gdb) po job
{
    EnableTransactions = 1;
    Label = "censored for the moment";
    LastExitStatus = 0;
    LimitLoadToSessionType = Aqua;
    MachServices =     {
        "censored for the moment" = 0;
    };
    OnDemand = 1;
    ProgramArguments =     (
        "/usr/libexec/launchproxyls",
        "censored for the moment"
    );
    TimeOut = 30;
    TransactionCount = "-1";
}
```

There's my job! I knew it was in there _somewhere_... And look at that `OnDemand` value! Amazing.

SO. Once again. This pull request _is about fixing sandbox issues_. The `enabled` property is a lazy as hell method of memoizing without stepping on the feet of the original code, but you can certainly feel free to gut that out if you prefer. However, the code you have now does not work as you seem to think it does when sandboxed.

Rather than tell me the code I'm contributing to you for free is "extraneous and unnecessary", "is not more sandbox friendly", "consumes more ram", "adds complication", and **"is not needed"**, you might want to make sure those statements are factually accurate.

**Comment by alexzielenski** [comment]
Apologies if my comments had offended you but in my implementation of this in a sandboxed environment had worked. If your code works for you, that's great.

**Comment by ttilley** [comment]
Out of curiosity, have you tried on 10.7.3? I've seen random reports of launchers suddenly not working. Mind giving it a test? I'm truly curious now.

**Comment by ttilley** [comment]
Significant changes have been made to the sandbox in 10.7.3 (devforums access required): https://devforums.apple.com/thread/138513?start=0&tstart=0

So... It is entirely possible that I'm only experiencing problems because I've been running 10.7.3 this whole time.

**Comment by alexzielenski** [comment]
Ah, and I on 10.7.2.

**Comment by ttilley** [comment]
Addendum: if you have your heart set on running `LSRegisterURL`, I investigated runtime sandbox detection and have a solution i'm relatively pleased with. it can't really verify directly that it's within a sandbox without using hackish methods that could break at any time, but it CAN detect the entitlements of the currently running code as well as what version of Foundation is currently in use. Together that's effectively the same thing.

I've gist'd my sandbox/codesign conveniences header here: https://gist.github.com/1737625

Thoughts? Also, do you mind re-opening this pull request if only for the purpose of feedback and collaboration?

**Comment by junjie** [comment]
Tried both the master and ttilley's fork on 10.7.3 for a sandboxed app.

The master didn't work for me. Among other things, the LSRegisterURL code was giving me trouble whenever it was being called in a sandbox environment. Even after fixing that portion of code, I couldn't get the setting to launch at login to stick using the master code. It never seems to be registered properly. 

The - (BOOL)startAtLogin code in master was always giving me NO.

ttilley's fork worked fine for me under 10.7.3 for a sandboxed app.

**Comment by ttilley** [comment]
Any chance this can get merged in?

**Pull request merged**
